[package]
name = "minecraft"
version = "0.1.0"
authors = ["Dylan McKay <me@dylanmckay.io>"]

[dependencies]
byteorder = "0.5.3"
mio = "0.5.1"
flate2 = "0.2.14"
nalgebra = "0.8.2"
hematite-nbt = "0.2.0"
uuid = "0.3.0"

[[bin]]
name = "client"
path = "tools/client.rs"

